=== coolguy0702/AppleInternal/Tests/libMicro/libmicro-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://stash.sd.apple.com/coreos/libmicro/libmicro-schema.json",
  "title": "libMicro",
  "description": "Describes a libMicro workload configuration",
  "type": "object",
  "required": [
    "name",
    "version",
    "description",
    "defaults",
    "tests"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
       "type": "string",
       "description": "schema the file conforms to"
    },
    "name": {
      "type": "string",
      "description": "name of the libMicro workload"
    },
    "version": {
      "type": "integer",
      "minimum": 0,
      "description": "Version of the libMicro workload. Allows workloads to keep the same name while having a different configuration"
    },
    "description": {
      "type": "string",
      "description": "Description of the libMicro workload"
    },
    "comments": {
      "type": "string",
      "description": "Comments on the workload"
    },
    "defaults": {
      "type": "object",
      "description": "default arguments passed to all tests in the workload"
    },
    "tests": {
      "type": "array",
      "description": "array containing tests to run",
      "items": {
        "$ref": "#/definitions/test"
      },
      "minItems": 1
    }
  },
  "definitions": {
    "test": {
      "type": "object",
      "allOf": [
        {
          "required": [
            "name",
            "cases"
          ],
          "properties": {
            "name": {
              "type": "string",
              "description": "semantic name of the libMicro test to run"
            },
            "binary": {
              "type": "string",
              "description": "name of the binary that will be run. If not set, name will be used",
              "default": "#name"
            },
            "defaults": {
              "type": "object",
              "description": "default arguments passed to all cases in the test. Overwrites global defaults"
            },
            "weight": {
              "type": "integer",
              "description": "weight of the test for calculation of the overall score",
              "minimum": 1
            },
            "cases": {
              "type": "array",
              "description": "list of the test cases (specified by a list of arguments passed to the test) that will be run",
              "items": {
                "type": "object",
                "properties": {
                  "baseline": {
                    "type": "number",
                    "description": "baseline value for a 1000 score",
                    "minimum": 0,
                    "exclusiveMinimum": true
                  }
                },
                "additionalProperties": true
              },
              "minItems": 1
            },
            "comments": {
              "type": "string"
            }
          }
        }
      ]
    }
  }
}

=== coolguy0702/AppleInternal/Tests/libMicro/libMicro_UNIX.json
{
  "$schema": "https://stash.sd.apple.com/coreos/libmicro/libmicro-schema.json",
  "name": "libMicro_UNIX",
  "version": 1,
  "description": "libMicro UNIX tests",
  "comments": "Baseline is n69",
  "defaults": {
    "batch-size": 2000,
    "duration": 1000,
    "samples": 100
  },
  "tests": [
    {
      "name": "getppid",
      "weight": 2,
      "cases": [
        {
          "baseline": 0.29002
        }
      ]
    },
    {
      "name": "chdir",
      "cases": [
        {
          "baseline": 0.88689
        }
      ]
    },
    {
      "name": "close",
      "cases": [
        {
          "baseline": 2.34996,
          "batch-size": 100
        }
      ]
    },
    {
      "name": "stat",
      "cases": [
        {
          "baseline": 5.23767,
          "batch-size": 500,
          "tmpdir": 1
        }
      ]
    },
    {
      "name": "fcntl",
      "cases": [
        {
          "baseline": 0.35058
        }
      ]
    },
    {
      "name": "fcntl_ndelay",
      "cases": [
        {
          "baseline": 0.47827
        }
      ]
    },
    {
      "name": "lseek",
      "defaults": {
        "batch-size": 200
      },
      "cases": [
        {
          "baseline": 0.60038,
          "buffer-size": "8k"
        }
      ]
    },
    {
      "name": "pwrite",
      "defaults": {
        "batch-size": 50,
        "temp-file": 1
      },
      "cases": [
        {
          "baseline": 1.86834,
          "size": "1k"
        },
        {
          "baseline": 2.30166,
          "size": "10k"
        },
        {
          "baseline": 10.32668,
          "size": "100k",
          "batch-size": 5
        }
      ]
    },
    {
      "name": "pread",
      "defaults": {
        "batch-size": 50,
        "temp-file": 1
      },
      "cases": [
        {
          "baseline": 1.30168,
          "buffer-size": "1k"
        },
        {
          "baseline": 1.72584,
          "buffer-size": "10k"
        },
        {
          "baseline": 9.79168,
          "buffer-size": "100k",
          "batch-size": 5
        }
      ]
    },
    {
      "name": "writev",
      "defaults": {
        "batch-size": 50,
        "temp-file": 1
      },
      "cases": [
        {
          "baseline": 3.02418,
          "buffer-size": "1k"
        },
        {
          "baseline": 14.92668,
          "buffer-size": "10k"
        },
        {
          "baseline": 111.4502,
          "buffer-size": "100k",
          "batch-size": 5
        }
      ]
    },
    {
      "name": "write",
      "defaults": {
        "batch-size": 50,
        "temp-file": 1
      },
      "cases": [
        {
          "baseline": 1.8125,
          "size": "1k"
        },
        {
          "baseline": 2.58584,
          "size": "10k"
        },
        {
          "baseline": 10.5086,
          "size": "100k",
          "batch-size": 5
        }
      ]
    },
    {
      "name": "read",
      "defaults": {
        "batch-size": 50,
        "temp-file": 1
      },
      "cases": [
        {
          "baseline": 1.33502,
          "buffer-size": "1k"
        },
        {
          "baseline": 2.13084,
          "buffer-size": "10k"
        },
        {
          "baseline": 10.2876,
          "buffer-size": "100k",
          "batch-size": 10
        }
      ]
    },
    {
      "name": "munmap",
      "binary": "munmap",
      "cases": [
        {
          "baseline": 0.81933,
          "mapping-length": "8k",
          "temp-file": 1
        },
        {
          "baseline": 0.79329,
          "mapping-length": "128k",
          "temp-file": 1
        },
        {
          "baseline": 0.64029,
          "mapping-length": "8k",
          "file": "MAP_ANON"
        },
        {
          "baseline": 0.64052,
          "mapping-length": "128k",
          "file": "MAP_ANON"
        }
      ]
    },
    {
      "name": "munmap_read",
      "binary": "munmap",
      "defaults": {
        "read-byte": 1,
        "batch-size": 1000
      },
      "cases": [
        {
          "baseline": 4.684,
          "mapping-length": "8k",
          "temp-file": 1
        },
        {
          "baseline": 4.83417,
          "mapping-length": "128k",
          "temp-file": 1,
          "batch-size": 100
        },
        {
          "baseline": 1.70521,
          "mapping-length": "8k",
          "file": "MAP_ANON"
        },
        {
          "baseline": 3.82417,
          "mapping-length": "128k",
          "file": "MAP_ANON",
          "batch-size": 100
        }
      ]
    },
    {
      "name": "munmap_write",
      "binary": "munmap",
      "defaults": {
        "write-byte": 1,
        "batch-size": 1000
      },
      "cases": [
        {
          "baseline": 1.83704,
          "mapping-length": "8k",
          "temp-file": 1
        },
        {
          "baseline": 4.03501,
          "mapping-length": "128k",
          "temp-file": 1,
          "batch-size": 100
        },
        {
          "baseline": 1.70683,
          "mapping-length": "8k",
          "file": "MAP_ANON"
        },
        {
          "baseline": 3.89959,
          "mapping-length": "128k",
          "file": "MAP_ANON",
          "batch-size": 100
        }
      ]
    },
    {
      "name": "mmap",
      "cases": [
        {
          "baseline": 1.75267,
          "mapping-length": "8k",
          "temp-file": 1
        },
        {
          "baseline": 1.77625,
          "mapping-length": "128k",
          "temp-file": 1
        },
        {
          "baseline": 0.83648,
          "mapping-length": "8k",
          "file": "MAP_ANON"
        },
        {
          "baseline": 0.85267,
          "mapping-length": "128k",
          "file": "MAP_ANON"
        }
      ]
    },
    {
      "name": "mmap_read",
      "binary": "mmap",
      "defaults": {
        "read-byte": 1,
        "batch-size": 1000
      },
      "cases": [
        {
          "baseline": 3.12379,
          "mapping-length": "8k",
          "temp-file": 1
        },
        {
          "baseline": 10.46328,
          "mapping-length": "128k",
          "temp-file": 1,
          "batch-size": 100
        },
        {
          "baseline": 4.65029,
          "mapping-length": "8k",
          "file": "MAP_ANON"
        },
        {
          "baseline": 24.0487,
          "mapping-length": "128k",
          "file": "MAP_ANON",
          "batch-size": 100
        }
      ]
    },
    {
      "name": "mmap_write",
      "binary": "mmap",
      "defaults": {
        "write-byte": 1,
        "batch-size": 1000
      },
      "cases": [
        {
          "baseline": 5.91879,
          "mapping-length": "8k",
          "temp-file": 1
        },
        {
          "baseline": 27.53125,
          "mapping-length": "128k",
          "temp-file": 1,
          "batch-size": 100
        },
        {
          "baseline": 4.48488,
          "mapping-length": "8k",
          "file": "MAP_ANON"
        },
        {
          "baseline": 23.585,
          "mapping-length": "128k",
          "file": "MAP_ANON",
          "batch-size": 100
        }
      ]
    },
    {
      "name": "pipe",
      "defaults": {
        "batch-size": 10
      },
      "cases": [
        {
          "baseline": 1.1619,
          "buffer-size": 1,
          "transport": "pipe",
          "mode": "st"
        },
        {
          "baseline": 14.3959,
          "buffer-size": 1,
          "transport": "pipe",
          "mode": "mt"
        },
        {
          "baseline": 14.9959,
          "buffer-size": 1,
          "transport": "pipe",
          "mode": "mp"
        }
      ]
    },
    {
      "name": "gettimeofday",
      "cases": [
        {
          "baseline": 0.03628
        }
      ]
    },
    {
      "name": "recurse",
      "cases": [
        {
          "baseline": 0.38238
        }
      ]
    },
    {
      "name": "fork",
      "comments": "bi-modal distribution ?",
      "cases": [
        {
          "baseline": 445.5745,
          "batch-size": 10
        }
      ]
    },
    {
      "name": "exit",
      "cases": [
        {
          "baseline": 191.2121,
          "batch-size": 10
        }
      ]
    },
    {
      "name": "posix_spawn",
      "cases": [
        {
          "baseline": 1756.9084,
          "batch-size": 10
        }
      ]
    },
    {
      "name": "pthread_create",
      "cases": [
        {
          "baseline": 24.89588,
          "batch-size": 32
        },
        {
          "baseline": 27.21973,
          "batch-size": 128
        }
      ]
    },
    {
      "name": "sigaction",
      "cases": [
        {
          "baseline": 0.33379
        }
      ]
    },
    {
      "name": "signal",
      "cases": [
        {
          "baseline": 2.92227
        }
      ]
    },
    {
      "name": "sigprocmask",
      "cases": [
        {
          "baseline": 0.73796
        }
      ]
    },
    {
      "name": "dup",
      "cases": [
        {
          "baseline": 0.59064
        }
      ]
    },
    {
      "name": "file_lock",
      "cases": [
        {
          "baseline": 1.8084,
          "batch-size": 10
        }
      ]
    },
    {
      "name": "cascade_mutex",
      "cases": [
        {
          "baseline": 0.1041,
          "batch-size": 1000
        },
        {
          "baseline": 111.34733,
          "batch-size": 5,
          "threads": 10
        },
        {
          "baseline": 4238.993,
          "batch-size": 5,
          "threads": 200
        }
      ]
    },
    {
      "name": "cascade_cond",
      "cases": [
        {
          "baseline": 0.27792,
          "batch-size": 100
        },
        {
          "baseline": 97.7345,
          "batch-size": 5,
          "threads": 10
        },
        {
          "baseline": 1249.74317,
          "batch-size": 5,
          "threads": 100
        }
      ]
    },
    {
      "name": "cascade_lockf",
      "cases": [
        {
          "baseline": 3.69292
        },
        {
          "baseline": 128.0876,
